### ISSUE TITLE
Image loop or GIF?

### ISSUE THREAD

**Issue by kingrun** [Kanium/flappinghead#8]
Hi just found your github and I am interested in flappinghead and the lip sync is pretty straight on as far as I've tested. I wanted to ask if there is a possibility to do a image loop like for example make the eyes blink on a timer on loop while having maybe 3-4 images for that. Or instead integrate a GIF into it I don't really know if it supports GIF images.

**Comment by Adrinus** [comment]
Hello, and thanks for the suggestion! The engine this program is based on does not natively support gifs, or any kind of idle animation: while I could potentially look into doing so, I don't have any plans in the near future to implement such a thing, but I do like the idea, so will keep it in mind for future builds.

As a workaround you might be able to add a prop that covers the eyes and appears to be closed eyes, and then automate a hotkey program to toggle the prop on and off at semi-random intervals.

**Comment by kingrun** [comment]
hmm that might actually work. I could just put the current eyes as blank transparent images and add some prop eyes. Ok ill give that a shot. Ill still be following this project as this has one of the closest lip sync's actually. Something like facerig or adobe character animator just have way too big of a delay to be used in real time. But this is perfect great job!

**Comment by Adrinus** [comment]
Thank you for the praise! The "Quality" control will affect the sync, so you might consider playing with it a bit for best sync to "complexity".
